/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as MedicalServicesRouteImport } from './routes/medical-services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FreeEyeCheckupRouteImport } from './routes/free-eye-checkup'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CancelPaymentRouteImport } from './routes/cancel-payment'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppointmentCancelledRouteImport } from './routes/appointment-cancelled'
import { Route as AppointmentCancellationConfirmationRouteImport } from './routes/appointment-cancellation-confirmation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ProductCategorySlugRouteImport } from './routes/product-category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalServicesRoute = MedicalServicesRouteImport.update({
  id: '/medical-services',
  path: '/medical-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEyeCheckupRoute = FreeEyeCheckupRouteImport.update({
  id: '/free-eye-checkup',
  path: '/free-eye-checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelPaymentRoute = CancelPaymentRouteImport.update({
  id: '/cancel-payment',
  path: '/cancel-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentCancelledRoute = AppointmentCancelledRouteImport.update({
  id: '/appointment-cancelled',
  path: '/appointment-cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentCancellationConfirmationRoute =
  AppointmentCancellationConfirmationRouteImport.update({
    id: '/appointment-cancellation-confirmation',
    path: '/appointment-cancellation-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategorySlugRoute = ProductCategorySlugRouteImport.update({
  id: '/product-category/$slug',
  path: '/product-category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointment-cancellation-confirmation': typeof AppointmentCancellationConfirmationRoute
  '/appointment-cancelled': typeof AppointmentCancelledRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-appointment': typeof BookAppointmentRoute
  '/cancel-payment': typeof CancelPaymentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-eye-checkup': typeof FreeEyeCheckupRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/medical-services': typeof MedicalServicesRoute
  '/my-account': typeof MyAccountRoute
  '/my-bookings': typeof MyBookingsRoute
  '/pharmacy': typeof PharmacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product-category/$slug': typeof ProductCategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointment-cancellation-confirmation': typeof AppointmentCancellationConfirmationRoute
  '/appointment-cancelled': typeof AppointmentCancelledRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/cancel-payment': typeof CancelPaymentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-eye-checkup': typeof FreeEyeCheckupRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/medical-services': typeof MedicalServicesRoute
  '/my-account': typeof MyAccountRoute
  '/my-bookings': typeof MyBookingsRoute
  '/pharmacy': typeof PharmacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product-category/$slug': typeof ProductCategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointment-cancellation-confirmation': typeof AppointmentCancellationConfirmationRoute
  '/appointment-cancelled': typeof AppointmentCancelledRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-appointment': typeof BookAppointmentRoute
  '/cancel-payment': typeof CancelPaymentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-eye-checkup': typeof FreeEyeCheckupRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/medical-services': typeof MedicalServicesRoute
  '/my-account': typeof MyAccountRoute
  '/my-bookings': typeof MyBookingsRoute
  '/pharmacy': typeof PharmacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product-category/$slug': typeof ProductCategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/appointment-cancellation-confirmation'
    | '/appointment-cancelled'
    | '/blog'
    | '/book-appointment'
    | '/cancel-payment'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/doctor'
    | '/facilities'
    | '/faqs'
    | '/forgot-password'
    | '/free-eye-checkup'
    | '/gallery'
    | '/login'
    | '/medical-services'
    | '/my-account'
    | '/my-bookings'
    | '/pharmacy'
    | '/privacy-policy'
    | '/search'
    | '/services'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/wishlist'
    | '/blog/$slug'
    | '/product-category/$slug'
    | '/product/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/appointment-cancellation-confirmation'
    | '/appointment-cancelled'
    | '/book-appointment'
    | '/cancel-payment'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/doctor'
    | '/facilities'
    | '/faqs'
    | '/forgot-password'
    | '/free-eye-checkup'
    | '/gallery'
    | '/login'
    | '/medical-services'
    | '/my-account'
    | '/my-bookings'
    | '/pharmacy'
    | '/privacy-policy'
    | '/search'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/wishlist'
    | '/blog/$slug'
    | '/product-category/$slug'
    | '/product/$slug'
    | '/services/$slug'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/appointment-cancellation-confirmation'
    | '/appointment-cancelled'
    | '/blog'
    | '/book-appointment'
    | '/cancel-payment'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/doctor'
    | '/facilities'
    | '/faqs'
    | '/forgot-password'
    | '/free-eye-checkup'
    | '/gallery'
    | '/login'
    | '/medical-services'
    | '/my-account'
    | '/my-bookings'
    | '/pharmacy'
    | '/privacy-policy'
    | '/search'
    | '/services'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/wishlist'
    | '/blog/$slug'
    | '/product-category/$slug'
    | '/product/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppointmentCancellationConfirmationRoute: typeof AppointmentCancellationConfirmationRoute
  AppointmentCancelledRoute: typeof AppointmentCancelledRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookAppointmentRoute: typeof BookAppointmentRoute
  CancelPaymentRoute: typeof CancelPaymentRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DoctorRoute: typeof DoctorRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreeEyeCheckupRoute: typeof FreeEyeCheckupRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MedicalServicesRoute: typeof MedicalServicesRoute
  MyAccountRoute: typeof MyAccountRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PharmacyRoute: typeof PharmacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  WishlistRoute: typeof WishlistRoute
  ProductCategorySlugRoute: typeof ProductCategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-services': {
      id: '/medical-services'
      path: '/medical-services'
      fullPath: '/medical-services'
      preLoaderRoute: typeof MedicalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-eye-checkup': {
      id: '/free-eye-checkup'
      path: '/free-eye-checkup'
      fullPath: '/free-eye-checkup'
      preLoaderRoute: typeof FreeEyeCheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-payment': {
      id: '/cancel-payment'
      path: '/cancel-payment'
      fullPath: '/cancel-payment'
      preLoaderRoute: typeof CancelPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment-cancelled': {
      id: '/appointment-cancelled'
      path: '/appointment-cancelled'
      fullPath: '/appointment-cancelled'
      preLoaderRoute: typeof AppointmentCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment-cancellation-confirmation': {
      id: '/appointment-cancellation-confirmation'
      path: '/appointment-cancellation-confirmation'
      fullPath: '/appointment-cancellation-confirmation'
      preLoaderRoute: typeof AppointmentCancellationConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-category/$slug': {
      id: '/product-category/$slug'
      path: '/product-category/$slug'
      fullPath: '/product-category/$slug'
      preLoaderRoute: typeof ProductCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppointmentCancellationConfirmationRoute:
    AppointmentCancellationConfirmationRoute,
  AppointmentCancelledRoute: AppointmentCancelledRoute,
  BlogRoute: BlogRouteWithChildren,
  BookAppointmentRoute: BookAppointmentRoute,
  CancelPaymentRoute: CancelPaymentRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DoctorRoute: DoctorRoute,
  FacilitiesRoute: FacilitiesRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreeEyeCheckupRoute: FreeEyeCheckupRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MedicalServicesRoute: MedicalServicesRoute,
  MyAccountRoute: MyAccountRoute,
  MyBookingsRoute: MyBookingsRoute,
  PharmacyRoute: PharmacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  WishlistRoute: WishlistRoute,
  ProductCategorySlugRoute: ProductCategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
